### PR TITLE
Relative unit for the radius (and more)

### PR DESCRIPTION
**Pull request by mymike00**
changed from `Devices.density` to `units.gu`
change the value if you like more another one

### CODE REVIEW

**Comment by mymike00** [comment]
okay, will do in the next days, when I'll find some spare time

**Comment by mymike00** [comment]
is there any direct proportion between `Devices.density` and `units.gu` ? Like (I invent) 1 `Devices.density` is equal to 3 `units.gu` ... so it would much easier substitute every occurrence, instead of changing one by one, testing if it's ok or not...

**Comment by Flohack74** [comment]
Well compare with what you found for the radius wehre you assumes gu 0.7 - what was the calculation before giving?

**Comment by mymike00** [comment]
from `5.5*Devices.density` to `units.gu(0.7)` should be about `1*Devices.density` is equal `units.gu(0.127)` but I'm not sure that `5.5` correspond to `units.gu(0.7)` ...

**Pull request merged**
